// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNhsnS1WzmeXfZCqmjNdnFYtbcTANf5Ok',
    appId: '1:745558004708:web:075b65e8444b46e03dedf1',
    messagingSenderId: '745558004708',
    projectId: 'rentcar-f37d1',
    authDomain: 'rentcar-f37d1.firebaseapp.com',
    storageBucket: 'rentcar-f37d1.appspot.com',
    measurementId: 'G-43D7E9MK3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2MvQnMj261c7tpRakiL9xUrfl1XTog98',
    appId: '1:745558004708:android:8618674c98370a9b3dedf1',
    messagingSenderId: '745558004708',
    projectId: 'rentcar-f37d1',
    storageBucket: 'rentcar-f37d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtCpp8Oal7JCnIr-OF3JGzGEfj6DlElD4',
    appId: '1:745558004708:ios:73688e0bfe6301243dedf1',
    messagingSenderId: '745558004708',
    projectId: 'rentcar-f37d1',
    storageBucket: 'rentcar-f37d1.appspot.com',
    iosBundleId: 'com.example.carRentalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtCpp8Oal7JCnIr-OF3JGzGEfj6DlElD4',
    appId: '1:745558004708:ios:73688e0bfe6301243dedf1',
    messagingSenderId: '745558004708',
    projectId: 'rentcar-f37d1',
    storageBucket: 'rentcar-f37d1.appspot.com',
    iosBundleId: 'com.example.carRentalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNhsnS1WzmeXfZCqmjNdnFYtbcTANf5Ok',
    appId: '1:745558004708:web:d35c25e0b83644ff3dedf1',
    messagingSenderId: '745558004708',
    projectId: 'rentcar-f37d1',
    authDomain: 'rentcar-f37d1.firebaseapp.com',
    storageBucket: 'rentcar-f37d1.appspot.com',
    measurementId: 'G-4EMPRFKV6H',
  );
}
